export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAILURE = "GET_USER_REQUEST"


export const GET_POKEMON_DATA_REQUEST = "GET_POKEMON_DATA_REQUEST"
export const GET_POKEMON_DATA_SUCCESS = "GET_POKEMON_DATA_SUCCESS"
export const GET_POKEMON_DATA_FAILURE = "GET_POKEMON_DATA_FAILURE"

export const GET_SINGLE_POKEMON_REQUEST = "GET_SINGLE_POKEMON_REQUEST"
export const GET_SINGLE_POKEMON_SUCCESS = "GET_SINGLE_POKEMON_SUCCESS"
export const GET_SINGLE_POKEMON_FAILURE = "GET_SINGLE_POKEMON_FAILURE"


export const GET_USER_LOGIN = "GET_USER_LOGIN"

export const GET_LOGOUT_USER = "GET_LOGOUT_USER"